### ISSUE TITLE
Support for Polylang

### ISSUE THREAD

**Issue by alexis3290** [johannheyne/acf-table-field-pro-support#2]
**Is your feature request related to a problem? Please describe.**
I'm using your plugin on my blog to compare camera, flash and other photographer accessories that I sell on my shop.
All my website is translated in three languages with Polylang, but unfortunately table are the only things that I can't translate in my posts.

**Describe the solution you'd like**
A support of Polylang. I know Polylang create X posts for X languages in different postype, and link data between them with custom fields.

**Describe alternatives you've considered**
No alternative :'(

**Additional context**
Polylang is now really common, because it's lighter and faster than WPML. Also they have a free and paid version with advanced featured like deepl Pro integration for easy translations. 
So I think that's a must have that you can include this feature in your PRO version. Most people should be okay to pay 49€ for this awesome feature.

**Comment by johannheyne** [comment]
I'll take a look at this and try to integrate a solution.

Thanks!

**Comment by alexis3290** [comment]
Nice ! 
Let me know if you want me to help to test / feedback.

**Comment by johannheyne** [comment]
Good news. I was able to make the table field translatable on Pages, Posts, Post Category with a simple adjustment in the table field plugin. Therefore I assume that the problem has generally been solved. I'll get in touch tomorrow and gratefully accept your test offer.

Thanks!

**Comment by johannheyne** [comment]
Hi, you can download and test the new plugin version 1.1.1 (the last one in the list) at your order page https://app.lemonsqueezy.com/my-orders/.

**Comment by alexis3290** [comment]
Ok I will order it, I never bought the pro version yet !

**Comment by johannheyne** [comment]
If the plugin doesn't work for you I can refund the money. Thanks!
